"""
backend/pipelines/pipelines.py

Every pipeline follows the same shape:
  1. try the real GPU model
  2. on GeoChatUnavailable / missing checkpoint / any load-time error,
     degrade to the deterministic fallback IF FLAGS.allow_*_fallback,
     else re-raise
  3. always run the deterministic geospatial engine on whatever pixel
     output was produced (real or fallback) -- geometry math is never
     itself a fallback, it's the trusted core
  4. wrap everything in an EvidenceContract via ProvenanceTracer
"""
from __future__ import annotations

from typing import Optional

from PIL import Image
import numpy as np

from backend.config.settings import PATHS, FLAGS
from backend.geospatial import engine as geo
from backend.evidence.contract import (
    ProvenanceTracer, build_evidence, compute_reliability, gsd_rating,
)
from backend.models.geochat.adapter import GeoChatAdapter, GeoChatUnavailable
from backend.models.changenet.model import (
    load_changenet, changenet_infer, classical_change_fallback, otsu_threshold,
)
from backend.models.dofa.adapter import DOFAAdapter, classical_fusion_fallback, BandMap


# ---------------------------------------------------------------------------
# 1. Single-image VQA
# ---------------------------------------------------------------------------

def run_vqa(image_path: str, question: str) -> dict:
    tracer = ProvenanceTracer()
    with tracer.timed("read_raster_info"):
        info = geo.read_raster_info(image_path)

    is_real, fallback_used, answer, model_conf = True, False, None, 0.8
    with tracer.timed("geochat_vqa_inference"):
        try:
            adapter = GeoChatAdapter()
            adapter.load()
            img = Image.open(image_path).convert("RGB")
            result = adapter.answer_vqa(img, question)
            adapter.unload()
            answer = result["answer"]
            model_conf = 0.85
        except GeoChatUnavailable as e:
            if not FLAGS.allow_geochat_fallback:
                raise
            is_real, fallback_used = False, True
            answer, model_conf = _vqa_heuristic_fallback(image_path, question), 0.4

    reliability, factors = compute_reliability(
        model_confidence=model_conf, registration_quality=1.0,
        gsd_resolution_rating=gsd_rating(info.gsd_x, "vqa"), fallback_used=fallback_used,
    )
    evidence = build_evidence(
        task="visual_question_answering", model="GeoChat-7B (4-bit NF4)" if is_real else "Heuristic band-statistics fallback",
        is_real_weights=is_real, fallback_used=fallback_used,
        inputs=[image_path], claim=answer, spatial_evidence=None,
        metrics={"gsd_m_per_px": round(info.gsd_x, 3)},
        reliability_score=reliability, reliability_factors=factors, tracer=tracer,
        warnings=[] if is_real else ["GeoChat checkpoint unavailable -- answer generated by "
                                      "deterministic band-statistics heuristic, not a VLM."],
    )
    return evidence.to_dict()


def _vqa_heuristic_fallback(image_path: str, question: str) -> str:
    """No language model available -- describes coarse scene statistics
    (brightness, band means, apparent water/vegetation fraction) rather
    than fabricating a free-text answer to an arbitrary question."""
    arr = geo.read_raster_array(image_path)
    band_means = arr.mean(axis=(1, 2))
    bright = float(arr.mean())
    return (
        f"[Fallback -- no GeoChat weights loaded] Cannot answer open-ended "
        f"question '{question}' without the VLM. Scene statistics: mean "
        f"brightness={bright:.1f}, per-band means={np.round(band_means, 1).tolist()}, "
        f"shape={arr.shape}. Load a GeoChat-7B checkpoint for real answers."
    )


# ---------------------------------------------------------------------------
# 2. Captioning
# ---------------------------------------------------------------------------

def run_captioning(image_path: str) -> dict:
    tracer = ProvenanceTracer()
    with tracer.timed("read_raster_info"):
        info = geo.read_raster_info(image_path)

    is_real, fallback_used, caption, model_conf = True, False, None, 0.85
    with tracer.timed("geochat_captioning_inference"):
        try:
            adapter = GeoChatAdapter()
            adapter.load()
            img = Image.open(image_path).convert("RGB")
            result = adapter.caption(img)
            adapter.unload()
            caption = result["caption"]
        except GeoChatUnavailable:
            if not FLAGS.allow_geochat_fallback:
                raise
            is_real, fallback_used, model_conf = False, True, 0.4
            caption = _caption_heuristic_fallback(image_path)

    reliability, factors = compute_reliability(
        model_confidence=model_conf, registration_quality=1.0,
        gsd_resolution_rating=gsd_rating(info.gsd_x, "captioning"), fallback_used=fallback_used,
    )
    evidence = build_evidence(
        task="scene_captioning", model="GeoChat-7B (4-bit NF4)" if is_real else "Heuristic statistics fallback",
        is_real_weights=is_real, fallback_used=fallback_used,
        inputs=[image_path], claim=caption, spatial_evidence=None,
        metrics={"width": info.width, "height": info.height, "bands": info.count},
        reliability_score=reliability, reliability_factors=factors, tracer=tracer,
    )
    return evidence.to_dict()


def _caption_heuristic_fallback(image_path: str) -> str:
    arr = geo.read_raster_array(image_path)
    bands = BandMap()
    veg_frac, water_frac = 0.0, 0.0
    try:
        from backend.models.dofa.adapter import ndwi, ndbi
        water_frac = float((ndwi(arr, bands) > 0.2).mean())
        veg_frac = float((ndbi(arr, bands) < -0.1).mean())
    except Exception:
        pass
    return (
        f"[Fallback -- no GeoChat weights loaded] Estimated composition from spectral "
        f"indices: ~{water_frac*100:.1f}% water-like pixels, ~{veg_frac*100:.1f}% "
        f"vegetation-like pixels. Load GeoChat-7B for a full semantic scene description."
    )


# ---------------------------------------------------------------------------
# 3. Grounding -> ground area
# ---------------------------------------------------------------------------

def run_grounding(image_path: str, referring_expression: str) -> dict:
    tracer = ProvenanceTracer()
    with tracer.timed("read_raster_info"):
        info = geo.read_raster_info(image_path)

    is_real, fallback_used, model_conf = True, False, 0.8
    with tracer.timed("geochat_grounding_inference"):
        try:
            adapter = GeoChatAdapter()
            adapter.load()
            img = Image.open(image_path).convert("RGB")
            result = adapter.ground(img, referring_expression)
            adapter.unload()
            bbox_norm = result["bbox_norm_ymin_xmin_ymax_xmax"]
        except GeoChatUnavailable:
            if not FLAGS.allow_geochat_fallback:
                raise
            is_real, fallback_used, model_conf = False, True, 0.35
            bbox_norm = _grounding_heuristic_fallback(image_path, referring_expression)

    with tracer.timed("denormalize_bbox"):
        bbox_px = geo.denormalize_bbox(bbox_norm, info.width, info.height)
        ymin, xmin, ymax, xmax = bbox_px

    with tracer.timed("affine_polygonization_and_area"):
        ring_native = geo.bbox_pixels_to_geo_polygon(info.transform, ymin, xmin, ymax, xmax)
        area_info = geo.geo_polygon_to_ground_area(ring_native, info.crs_epsg)

    feature_collection = {
        "type": "FeatureCollection",
        "features": [{
            "type": "Feature",
            "properties": {"referring_expression": referring_expression, **{
                k: v for k, v in area_info.items() if k != "utm_ring"}},
            "geometry": {"type": "Polygon", "coordinates": [[[round(x, 6), round(y, 6)] for x, y in ring_native]]},
        }],
    }

    reliability, factors = compute_reliability(
        model_confidence=model_conf, registration_quality=1.0,
        gsd_resolution_rating=gsd_rating(info.gsd_x, "grounding"), fallback_used=fallback_used,
    )
    claim = (
        f"Located '{referring_expression}' covering {area_info['area_m2']:,.0f} m² "
        f"({area_info['area_ha']:.2f} ha)."
    )
    evidence = build_evidence(
        task="visual_grounding", model="GeoChat-7B (4-bit NF4) + Affine Geometry Engine" if is_real
        else "Saliency-heuristic grounding + Affine Geometry Engine",
        is_real_weights=is_real, fallback_used=fallback_used,
        inputs=[image_path], claim=claim, spatial_evidence=feature_collection,
        metrics=area_info, reliability_score=reliability, reliability_factors=factors, tracer=tracer,
        warnings=[] if is_real else ["No GeoChat checkpoint -- bounding box from a generic "
                                      "saliency heuristic, not text-grounded localization."],
    )
    return evidence.to_dict()


def _grounding_heuristic_fallback(image_path: str, referring_expression: str) -> list:
    """No VLM available -- returns the bounding box of the single largest
    high-contrast connected region as a coarse saliency proxy. Honest
    about being untargeted (ignores the referring expression's semantics)."""
    arr = geo.read_raster_array(image_path)
    gray = arr.mean(axis=0)
    thresh = np.percentile(gray, 90)
    mask = (gray >= thresh).astype(np.uint8)
    ys, xs = np.where(mask)
    if len(ys) == 0:
        h, w = gray.shape
        return [400, 400, 600, 600]  # normalized-1000 center box, last resort
    ymin, ymax, xmin, xmax = ys.min(), ys.max(), xs.min(), xs.max()
    h, w = gray.shape
    return [ymin / h * 1000, xmin / w * 1000, ymax / h * 1000, xmax / w * 1000]


# ---------------------------------------------------------------------------
# 4. Bi-temporal change detection / change-VQA
# ---------------------------------------------------------------------------

def run_change_detection(image_t1: str, image_t2: str, query: Optional[str] = None,
                          threshold: Optional[float] = None) -> dict:
    tracer = ProvenanceTracer()
    with tracer.timed("read_raster_info"):
        info_t1 = geo.read_raster_info(image_t1)
        info_t2 = geo.read_raster_info(image_t2)

    with tracer.timed("validate_temporal_pair"):
        pair_check = geo.validate_bitemporal_pair(info_t1, info_t2)
        if not pair_check.is_valid:
            raise ValueError(f"Bi-temporal pair failed validation: {pair_check.reasons}")

    with tracer.timed("read_raster_arrays"):
        arr_t1 = geo.read_raster_array(image_t1)
        arr_t2 = geo.read_raster_array(image_t2)
        min_c = min(arr_t1.shape[0], arr_t2.shape[0])
        arr_t1, arr_t2 = arr_t1[:min_c], arr_t2[:min_c]

    is_real, fallback_used, model_conf = True, False, 0.85
    with tracer.timed("changenet_inference"):
        try:
            model = load_changenet(PATHS.changenet / "changenet.pt", in_channels=min_c)
            probs = changenet_infer(model, arr_t1, arr_t2)
        except (FileNotFoundError, RuntimeError):
            if not FLAGS.allow_changenet_fallback:
                raise
            is_real, fallback_used, model_conf = False, True, 0.55
            probs = classical_change_fallback(arr_t1, arr_t2)

    with tracer.timed("threshold_selection"):
        thresh_used = threshold if threshold is not None else otsu_threshold(probs)

    with tracer.timed("affine_polygonization_and_area"):
        clusters = geo.mask_to_geo_clusters(probs, info_t1.transform, info_t1.crs_epsg,
                                             threshold=thresh_used)

    total_area_m2 = sum(c["area_m2"] for c in clusters)
    changed_px = int((probs >= thresh_used).sum())
    change_percent = round(100.0 * changed_px / probs.size, 2)

    features = [{
        "type": "Feature",
        "properties": {"cluster_id": c["cluster_id"], "area_m2": c["area_m2"], "area_ha": c["area_ha"]},
        "geometry": {"type": "Polygon", "coordinates": [c["ring_native_crs"]]},
    } for c in clusters]
    feature_collection = {"type": "FeatureCollection", "features": features}

    narrative = (
        f"Bi-temporal analysis detected {change_percent}% surface alteration across "
        f"{total_area_m2:,.0f} m² ({total_area_m2/10000:.2f} ha) in {len(clusters)} distinct "
        f"cluster(s)."
    )
    if query:
        narrative = f"{narrative} (query: \"{query}\")"

    reliability, factors = compute_reliability(
        model_confidence=model_conf, registration_quality=pair_check.overlap_fraction,
        gsd_resolution_rating=gsd_rating(info_t1.gsd_x, "change_detection"), fallback_used=fallback_used,
    )
    evidence = build_evidence(
        task="bitemporal_change_detection",
        model="Siamese ChangeNet + Affine Geometry Engine" if is_real
        else "Classical spectral-difference (Otsu) + Affine Geometry Engine",
        is_real_weights=is_real, fallback_used=fallback_used,
        inputs=[image_t1, image_t2], claim=narrative, spatial_evidence=feature_collection,
        metrics={
            "change_percent": change_percent, "total_area_m2": round(total_area_m2, 2),
            "total_area_ha": round(total_area_m2 / 10000, 4), "cluster_count": len(clusters),
            "threshold_used": round(float(thresh_used), 4), "overlap_fraction": pair_check.overlap_fraction,
        },
        reliability_score=reliability, reliability_factors=factors, tracer=tracer,
        warnings=pair_check.reasons + ([] if is_real else
            ["No ChangeNet checkpoint -- mask from classical spectral differencing, "
             "not a trained Siamese network."]),
    )
    return evidence.to_dict()


# ---------------------------------------------------------------------------
# 5. Optical + SAR fusion
# ---------------------------------------------------------------------------

def run_fusion_optical_sar(optical_path: str, sar_path: str, query: Optional[str] = None) -> dict:
    tracer = ProvenanceTracer()
    with tracer.timed("read_raster_info"):
        info_opt = geo.read_raster_info(optical_path)
        info_sar = geo.read_raster_info(sar_path)

    with tracer.timed("validate_pair_overlap"):
        pair_check = geo.validate_bitemporal_pair(info_opt, info_sar, min_overlap=0.6)
        # not truly "bitemporal" but the same overlap/CRS/GSD check applies

    with tracer.timed("read_raster_arrays"):
        arr_opt = geo.read_raster_array(optical_path)
        sar_raw = geo.read_raster_array(sar_path)[0]
        # Storage convention (see scripts/seed_demo_data.py and any SAR
        # ingestion step): sigma-nought dB is stored as uint16 via
        # (db + 30) * 1000 to avoid float rasters for the demo pipeline.
        # Real Sentinel-1 GRD products are typically float32 dB already --
        # detect and skip descaling if the array already looks like dB
        # (i.e. has negative or small-magnitude values).
        if sar_raw.max() > 1000:  # heuristic: looks like the scaled uint16 convention
            sar = sar_raw / 1000.0 - 30.0
        else:
            sar = sar_raw

    is_real, fallback_used, model_conf = False, True, 0.6  # DOFA real path is a documented stub above
    with tracer.timed("dofa_or_fallback_fusion"):
        fusion = classical_fusion_fallback(arr_opt, sar)

    with tracer.timed("polygonize_agreement_layers"):
        water_clusters = geo.mask_to_geo_clusters(fusion.water_agreement, info_opt.transform,
                                                    info_opt.crs_epsg, threshold=0.5)
        builtup_clusters = geo.mask_to_geo_clusters(fusion.builtup_agreement, info_opt.transform,
                                                      info_opt.crs_epsg, threshold=0.5)
        disagreement_clusters = geo.mask_to_geo_clusters(fusion.water_disagreement, info_opt.transform,
                                                           info_opt.crs_epsg, threshold=0.5)

    def _fc(clusters, label):
        return [{
            "type": "Feature",
            "properties": {"layer": label, "cluster_id": c["cluster_id"], "area_ha": c["area_ha"]},
            "geometry": {"type": "Polygon", "coordinates": [c["ring_native_crs"]]},
        } for c in clusters]

    feature_collection = {
        "type": "FeatureCollection",
        "features": _fc(water_clusters, "water_confirmed") + _fc(builtup_clusters, "builtup_confirmed")
        + _fc(disagreement_clusters, "optical_only_flag_possible_cloud_shadow"),
    }

    water_area_ha = sum(c["area_ha"] for c in water_clusters)
    built_area_ha = sum(c["area_ha"] for c in builtup_clusters)
    flagged_ha = sum(c["area_ha"] for c in disagreement_clusters)

    narrative = (
        f"Cross-modal analysis confirms {water_area_ha:.2f} ha of water and "
        f"{built_area_ha:.2f} ha of built-up area where optical and SAR agree. "
        f"{flagged_ha:.2f} ha flagged as optical-only water signal (possible cloud "
        f"shadow false alarm, unconfirmed by radar backscatter). Cross-modal "
        f"consistency index: {fusion.cross_modal_consistency_index:.0%}."
    )
    if query:
        narrative = f"{narrative} (query: \"{query}\")"

    reliability, factors = compute_reliability(
        model_confidence=model_conf, registration_quality=pair_check.overlap_fraction,
        gsd_resolution_rating=gsd_rating(info_opt.gsd_x, "fusion"), fallback_used=fallback_used,
    )
    evidence = build_evidence(
        task="optical_sar_fusion", model="Classical NDWI/NDBI + SAR backscatter thresholding "
        "(DOFA checkpoint not loaded)",
        is_real_weights=is_real, fallback_used=fallback_used,
        inputs=[optical_path, sar_path], claim=narrative, spatial_evidence=feature_collection,
        metrics={
            "water_confirmed_ha": round(water_area_ha, 4),
            "builtup_confirmed_ha": round(built_area_ha, 4),
            "optical_only_flagged_ha": round(flagged_ha, 4),
            "cross_modal_consistency_index": fusion.cross_modal_consistency_index,
        },
        reliability_score=reliability, reliability_factors=factors, tracer=tracer,
        warnings=["DOFA checkpoint not wired in -- see backend/models/dofa/adapter.py; "
                  "results use classical spectral-index + SAR-threshold fusion."],
    )
    return evidence.to_dict()


# ---------------------------------------------------------------------------
# 6. Golden mission (SIH demo Mission 02): full urban-expansion workflow
# ---------------------------------------------------------------------------

def run_golden_mission_urban_expansion(image_t1: str, image_t2: str, query: str) -> dict:
    """Combines change detection with a narrative summary suitable for
    the PDF dossier exporter. Thin orchestration on top of
    run_change_detection so the golden-mission demo and the general
    change-VQA path share one source of truth."""
    result = run_change_detection(image_t1, image_t2, query=query)
    result["task"] = "golden_mission_urban_expansion"
    return result
